const $ = id => document.getElementById(id)

export const timerDisplay = $('timerDisplay'), timerRound = $('timerRound')
export const timerStart = $('timerStart'), timerResetBtn = $('timerReset')
export const timerSettings = $('timerSettings')
export const timerTip = $('timerTip'), timerTipIcon = $('timerTipIcon'), timerTipText = $('timerTipText'), timerTipSource = $('timerTipSource')
export const focusBtn = $('focusBtn'), focusOverlay = $('focusOverlay')
export const focusTimerDisplay = $('focusTimerDisplay'), focusTimerRound = $('focusTimerRound')
export const focusStart = $('focusStart'), focusResetBtn = $('focusReset')
export const focusTip = $('focusTip'), focusTipIcon = $('focusTipIcon'), focusTipText = $('focusTipText'), focusTipSource = $('focusTipSource'), focusExit = $('focusExit')
export const settingsModal = $('settingsModal'), settingsClose = $('settingsClose')
export const settingsFocus = $('settingsFocus'), settingsShort = $('settingsShort'), settingsLong = $('settingsLong'), settingsRounds = $('settingsRounds'), settingsAutoStart = $('settingsAutoStart'), settingsSave = $('settingsSave')
export const statToday = $('statToday'), statWeek = $('statWeek'), statStreak = $('statStreak'), statMinutes = $('statMinutes')
export const tipsContainer = $('tipsContainer')
export const sidebarOverlay = $('sidebarOverlay'), hamburger = $('hamburger'), sidebarClose = $('sidebarClose'), themeBtn = $('themeBtn'), sidebarLang = $('sidebarLang')
export const taskInput = $('taskInput'), taskWrap = $('taskWrap'), taskDone = $('taskDone'), taskDoneText = $('taskDoneText')
export const chart = $('chart'), chartLabels = $('chartLabels')
